apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "200ms"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "200ms"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header x-prezly-env '{"PREZLY_ACCESS_TOKEN":"bKcab_Iwaab_d56f0ee55daba647b9a86f9d944e4dbe60f58e2b"}';
  labels:
    ingress-class: nginx
    reverse-proxy: "false"
    tls-enabled: "true"
    auth: "false"
    custom-tls: "false"
    tier: themes
  name: theme-nextjs-heartbeat.prezly.net
  namespace: themes
spec:
  rules:
  - host: theme-nextjs-heartbeat.prezly.net
    http:
      paths:
      - backend:
          serviceName: theme-nextjs-heartbeat
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - theme-nextjs-heartbeat.prezly.net
    secretName: theme-nextjs-heartbeat.prezly.net